export const AUTH_REQUEST = 'AUTH/AUTH_REQUEST'
export const SUCCESS_REQUEST = 'AUTH/SUCCESS_REQUEST'
export const INIT_USER_INFO = "AUTH/INIT_USER_INFO"
export const ADD_NEW_USER = "CHAT/ADD_NEW_USER"
export const ADD_NEW_MESSAGE = "CHAT/ADD_NEW_MESSAGE"